version: '3.8'
services:
  minecraft-server:
    container_name: minecraft
    image: audeldiaz/minecraft-server:1.19
    build: ./server
    volumes:
      - ./world:/usr/src/minecraft/world
      - ./server/server.properties:/usr/src/minecraft/server.properties
    ports:
      - 25565:25565
      - 19132:19132
    dns:
      - 8.8.8.8
      - 8.8.4.4
  
  rcon-web:
    image: itzg/rcon
    ports:
      - 4326:4326
      - 4327:4327
    env_file: .env
